# This is free software, lisence use MIT.
# Copyright (C) https://github.com/yfdoor

name: PVE-Kernel-CI

# 触发条件
on:
  # push:
  #  branches:
  #   - master
  schedule:
     - cron: 0 0 * * 3
  # release:
  #   types: [published]
  # watch:
  #  types: [started]

# 环境变量
env:
  REPO_BRANCH: pve-kernel-5.3

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      # 项目初始
      - name: Code Checkout
        uses: actions/checkout@master

      # 其他分支
      - name: Branch Checkout
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*   

      # 空间清理
      - name: Space Cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d/*
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo wget -qO - http://download.proxmox.com/debian/proxmox-ve-release-6.x.gpg | sudo apt-key add -
          sudo echo "deb http://download.proxmox.com/debian/pve buster pve-no-subscription" | sudo tee /etc/apt/sources.list.d/pve-install-repo.list
          sudo apt-get update
          sudo apt-get install git nano screen patch fakeroot build-essential devscripts libncurses5 libncurses5-dev libssl-dev bc flex bison libelf-dev libaudit-dev libgtk2.0-dev libperl-dev asciidoc xmlto gnupg gnupg2 rsync lintian debhelper libdw-dev libnuma-dev libslang2-dev sphinx-common asciidoc-base automake cpio dh-python file gcc kmod libiberty-dev libpve-common-perl libtool perl-modules python-minimal sed tar zlib1g-dev
          sudo echo "deb http://cz.archive.ubuntu.com/ubuntu eoan main" | sudo tee /etc/apt/sources.list.d/eoan_package.list
          sudo apt-get update
          sudo apt-get install lz4
          sudo apt-get -y autoremove --purge
          sudo apt-get clean
          df -h

      # 下载源码
      - name: Clone Code
        run: |
          git clone git://git.proxmox.com/git/pve-kernel.git -b $REPO_BRANCH

      # 修改文件
      - name: Modify Code
        run: |
          cp -f patches/kernel/* pve-kernel/patches/kernel/

      # 开始编译
      - name: Compile File
        run: |
          cd pve-kernel
          make V=s

      # 准备文件
      - name: Organize File
        run: |
          git checkout Kernel-Package
          mv -f pve-kernel/*.deb ./
          mkdir -p PVE && cp -rf *.deb PVE
          ls pve-kernel*.deb | xargs -d _ | awk '{print $2}'| xargs echo>tmp.txt
          export FNAME="$(cat tmp.txt)"
          mkdir -p $FNAME && mv -f *.deb $FNAME
          cd $FNAME
          zip -r PVE_Kernel_yfdoor_$FNAME.zip *       

      # 上传文件
      - name: Upload File
        uses: actions/upload-artifact@master
        with:
          name: PVE_Kernel_yfdoor
          path: PVE

      # 更新项目
      - name: Upload Branch
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          sudo rm -rf pve-kernel PVE tmp.txt .git*
          git init
          git config user.name "yfdoor"
          git config user.email "yfdoor@github.com"          
          git add .
          git commit -m "Update PVE-Kernel Package"
          git push --force --quiet https://$GITHUB_TOKEN@github.com/yfdoor/PVE-Kernel.git HEAD:Kernel-Package
