# This is free software, lisence use MIT.
# Copyright (C) https://github.com/yfdoor

name: PVE-Kernel-CI

# 触发条件
on:
  # push:
  #  branches:
  #   - master
  schedule:
     - cron: 0 0 * * 3
  # release:
  #   types: [published]
  watch:
    types: [started]

# 环境变量
env:
  REPO_BRANCH: pve-kernel-5.3

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      # 项目初始
      - name: Code Checkout
        uses: actions/checkout@master

      # 其他分支
      - name: Branch Checkout
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*   

      # 空间清理
      - name: Space Cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /swapfile /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc 
          sudo wget http://download.proxmox.com/debian/proxmox-ve-release-6.x.gpg -O /etc/apt/trusted.gpg.d/proxmox-ve-release-6.x.gpg
          sudo chmod +r /etc/apt/trusted.gpg.d/proxmox-ve-release-6.x.gpg
          sudo chmod a+w /etc/apt/sources.list
          sudo -E echo "deb http://download.proxmox.com/debian/pve buster pve-no-subscription" >>/etc/apt/sources.list
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install git nano screen patch fakeroot build-essential devscripts libncurses5 libncurses5-dev libssl-dev bc flex bison libelf-dev libaudit-dev libgtk2.0-dev libperl-dev asciidoc xmlto gnupg gnupg2 rsync lintian debhelper libdw-dev libnuma-dev libslang2-dev sphinx-common asciidoc-base automake cpio dh-python file gcc kmod libiberty-dev  libtool perl-modules python-minimal sed tar zlib1g-dev liblz4-tool idn
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          df -h
      
      # 准备依赖    
      - name:  Install proxmox depends
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          git clone git://git.proxmox.com/git/proxmox-acme.git -b master proxmox-acme
          cd proxmox-acme
          sed -i "s/8.30/8.28/g" debian/control
          sed -i "s/7.64/7.58/g" debian/control 
          sed -i "s/4.7/4.4/g" debian/control
          sed -i "/libpve-common-perl (>= 6~),/d" debian/control
          make 
          sudo dpkg -i libproxmox-acme-perl*.deb
          sudo -E apt-get -qq install libpve-common-perl
          cd ../
        
      # 下载源码
      - name: Clone Code
        run: |
          git clone git://git.proxmox.com/git/pve-kernel.git -b $REPO_BRANCH

      # 修改文件
      - name: Modify Code
        run: |
          cd pve-kernel
          sed -i "s/106 @@/105 @@/g" patches/kernel/0003-pci-Enable-overrides-for-missing-ACS-capabilities-4..patch
          sed -i "/pci_find_ext_capability(dev, PCI_EXT_CAP_ID_ACS))/d" patches/kernel/0003-pci-Enable-overrides-for-missing-ACS-capabilities-4..patch
          sed -i "s/(dev) ||/(dev))/g" patches/kernel/0003-pci-Enable-overrides-for-missing-ACS-capabilities-4..patch

      # 修正LZ4
      - name: Fix lz4 build deps
        run: |
          cd pve-kernel
          sed -i "s/lz4/liblz4-1/g" debian/control.in
        
      # 开始编译
      - name: Compile File
        run: |
          cd pve-kernel
          make V=s

      # 准备文件
      - name: Organize File
        run: |
          git checkout Kernel-Package
          mv -f pve-kernel/*.deb ./
          mkdir -p PVE && cp -rf *.deb PVE
          ls pve-kernel*.deb | xargs -d _ | awk '{print $2}'| xargs echo>tmp.txt
          export FNAME="$(cat tmp.txt)"
          mkdir -p $FNAME && mv -f *.deb $FNAME
          cd $FNAME
          zip -r PVE_Kernel_yfdoor_$FNAME.zip *       

      # 上传文件
      - name: Upload File
        uses: actions/upload-artifact@master
        with:
          name: PVE_Kernel_yfdoor
          path: PVE

      # 更新项目
      - name: Upload Branch
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          sudo rm -rf pve-kernel PVE tmp.txt .git*
          git init
          git config user.name "yfdoor"
          git config user.email "yfdoor@github.com"          
          git add .
          git commit -m "Update PVE-Kernel Package"
          git push --force --quiet https://$GITHUB_TOKEN@github.com/yfdoor/PVE-Kernel.git HEAD:Kernel-Package
